version: '3'

services:
  httpd:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:delegated
    command: /bin/sh -c "while sleep 1000; do :; done"